### ISSUE TITLE
Servicefehler "error null"

### ISSUE THREAD

**Issue by SoullessStone** [mobislan/ChangePush#1]
Als Product Owner der Applikation ChangePush will ich, dass die Ursache von Fehlern bekannt ist, damit der Zweck der Applikation erfüllt ist.

**IST**
Der Service der ChangePush-App hat einen Fehler, dessen Ursache unbekannt ist.
**SOLL**
Die Ursache des Fehlers ist bekannt und Folgemassnahmen sind aufgeplant und mit dem PO abgesprochen.

![slavi](https://user-images.githubusercontent.com/10846282/38720479-ac8e3444-3ef6-11e8-804a-37fd4c877da7.jpg)

**Comment by mobislan** [comment]
Wont Fix

**Comment by SoullessStone** [comment]
Fixed, getestet und abgenommen.
